import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import gameplayRouter from "./gameplay";
import storyRouter from "./story";
import rankingRouter from "./ranking";
import socialRouter from "./social";
import aiRouter from "./ai";
import aiQuestionsRouter from "./aiQuestions";
import aiCharactersRouter from "./aiCharacters";
import prestigeRouter from "./prestige";
import skillTreeRouter from "./skillTree";
import tournamentsRouter from "./tournaments";
import shopRouter from "./shop";
import worldEventsRouter from "./worldEvents";
import analyticsRouter from "./analytics";
import antiCheatRouter from "./antiCheat";
import missionRouter from "./mission";
import tacticalRouter from "./tactical";
import teamOpsRouter from "./teamOps";
import stageRouter from "./stage";
import adminRouter from "./admin";
import aiOpponentRouter from "./aiOpponent";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(gameplayRouter);
router.use(storyRouter);
router.use(rankingRouter);
router.use(socialRouter);
router.use(aiRouter);
router.use(aiQuestionsRouter);
router.use(aiCharactersRouter);
router.use(prestigeRouter);
router.use(skillTreeRouter);
router.use(tournamentsRouter);
router.use(shopRouter);
router.use(worldEventsRouter);
router.use(analyticsRouter);
router.use(antiCheatRouter);
router.use(missionRouter);
router.use(tacticalRouter);
router.use(teamOpsRouter);
router.use(stageRouter);
router.use(aiOpponentRouter);
router.use(adminRouter);

export default router;
